name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack and push
      env:
        PROJECT_NAME: AutoMapper.Extensions.ExpressionMapping
        DEPLOY_PACKAGE_URL: https://nuget.api.1stbet.com/v3/index.json
        DEPLOY_PACKAGE_API_KEY: ${{ secrets.NUGET_API_KEY }}
        REPO: ${{ github.repository }}
        REPO_OWNER: ${{ github.repository_owner }}
      run: ./Pack_Push.ps1
      shell: pwsh
